name: ci

on: [push]

env:
  DOCKER_BUILD: docker build --cache-from $TARGET --cache-from $TARGET_LATEST --build-arg SUFFIX --build-arg PREFIX -t ${PREFIX}${NAME}${SUFFIX} ${FOLDER}
  REGISTRY: localhost:5000
  PREFIX: "${{ secrets.DOCKER_USERNAME }}/"
  SUFFIX: ""
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
  # for non-released pkg
  extra_layer:
    runs-on: ubuntu-latest
    needs: builder
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Get Branch
        id: extract_branch
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF} | cut -d'/' -f3)
      - run: echo ${{ steps.extract_branch.outputs.branch }}
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: ./${{ github.job }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
                     "PREFIX=${{ env.PREFIX }}"
                     "SUFFIX=:${{ steps.extract_branch.outputs.branch }}"
  base_nav:
    runs-on: ubuntu-latest
    needs: extra_layer
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        env:
          DOCKER_BUILDKIT: 1
        with:
          image: ${{ env.PREFIX }}${{ github.job }}
          tags: ${{ github.branch }}
          registry: docker.io
          buildArgs: PREFIX=${{ env.PREFIX }}, SUFFIX=\:\${{ github.branch }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./mobile_base_system/src-gen/base_nav/Dockerfile
