name: ci

on: [push]

env:
  DOCKER_BUILD: docker build --cache-from $TARGET --cache-from $TARGET_LATEST --build-arg SUFFIX --build-arg PREFIX -t ${PREFIX}${NAME}${SUFFIX} ${FOLDER}
  REGISTRY: localhost:5000
  PREFIX: "${{ secrets.DOCKER_USERNAME }}/"
  SUFFIX: ""
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ github.job }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=raw,value=latest
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
        
  base_nav:
    runs-on: ubuntu-latest
    needs: builder
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.PREFIX}}/${{ github.job }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
      -
        name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        env:
          DOCKER_BUILDKIT: 1
        with:
          image: ${{ github.job }}
          tags: ${{ github.branch }}
          registry: docker.io
          buildArgs: PREFIX=${{ env.PREFIX }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./mobile_base_system/src-gen/base_nav/Dockerfile
